---
- name: Backup Cisco Router or Switch
  hosts: IOS
  connection: network_cli
  gather_facts: false

  tasks:
     
    - name: Get running-config and save it
      ios_config:
       backup: yes
       backup_path: /var/lib/awx/projects/
