---
- name: Backup Cisco Router or Switch
  hosts: IOS
  connection: network_cli
  gather_facts: false

  tasks:

    - name: Accept ansible Inventory hostname
      ios_facts:
        gather_subset: all

    - name: Get current date 
      local_action: command date +%Y-%b-%d
      register: date

    - name: Get current time
      local_action: command date +%H:%M
      register: time
    

    - name: Create a directory if it does not exist
      ansible.builtin.file:
       path: /home/backup
       state: directory
      
    - name: Get running-config and save it
      ios_config:
       backup: yes
       backup_options:
         #ansible_host = getting device IP, ansible_net_hostname = getting device hostname
         filename: "{{ inventory_hostname }}.txt"
         #Please change /home/hawar/Desktop to your direcotry
         #Every time create a new directory under named date and time
         dir_path: "/home/backup/{{ inventory_hostname }}.txt"
